Update README.md
Tribe-Turing/be_tribe pull request #39
Opened 2022-05-25 17:38 UTC by samivari

# Description
Added content to ReadMe File... Needs JSON responses to be complete

2022-05-25 19:04 UTC, glsorensen requested changes
Looks good once I get you the Postman Docs, and the schema image is updated

2022-05-25 19:04 UTC, glsorensen commented on README.md
> +![faraday](https://img.shields.io/badge/faraday-red)
Nice badges!

2022-05-26 21:03 UTC, samivari reviewed
ReadMe updated

2022-05-26 21:03 UTC, samivari reviewed
changes reviewed

2022-05-26 21:30 UTC, merged